spring.application.name=backend

# Server Port (Matches your React API calls)
server.port=8080

# Explicitly tell Spring Boot to load the .env file
spring.config.import=optional:file:.env

# MongoDB Atlas Connection (Pulls from your .env file)
spring.data.mongodb.uri=${MONGO_URI}